# Generated by Django 4.2.1 on 2023-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_variants"),
        ("core", "0003_alter_category_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="products.product"
            ),
        ),
    ]
