# Generated by Django 4.2.1 on 2023-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_cartorder_price_alter_cartorderproducts_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorderproducts",
            name="order",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="productimages",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wishlist_model",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wishlist_model",
            name="user",
        ),
        migrations.AlterField(
            model_name="vendor",
            name="title",
            field=models.CharField(default="phoenixify", max_length=100),
        ),
        migrations.DeleteModel(
            name="CartOrder",
        ),
        migrations.DeleteModel(
            name="CartOrderProducts",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductImages",
        ),
        migrations.DeleteModel(
            name="ProductReview",
        ),
        migrations.DeleteModel(
            name="wishlist_model",
        ),
    ]
