# Generated by Django 4.2.1 on 2023-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="variants",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="products",
                to="products.productvariant",
            ),
        ),
    ]
