# Generated by Django 4.2.1 on 2023-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_variants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="variants",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.productvariant"
            ),
        ),
    ]
